[package]
name = "matching-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
strsim = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "matching_engine"
crate-type = ["lib", "cdylib"]
